### ISSUE TITLE
Plans for tvOS?

### ISSUE THREAD

**Issue by tvOSPopcorn** [v2tmobile/ios-video-youtube-application#3]
Hi 👋🏻

I'm curious so I thought I'd ask but any plans to migrate your Application to Apple TV 4? Most of the backend would stay the same it'd just be the UI which would require quite a bit of work? Is this something that you've got planned?

Reason I'm asking is bc the current YouTube Application is terrible

**Comment by v2tmobile** [comment]
Thank you for your interesting.
I have not plan to migrate this repository to tvOS. But most likely I will have a plan to release a new open source about Youtube Application written in  Objective C.
